---
title: "Homework"
date: 2020-11-21T20:44:12-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```


## Introduction
Insert text herer.

## Reading data
```{r warning=F, message=F}
library(dplyr)
library(ggplot2)
stats <- read.csv("Players_Stats.csv")
score <- read.csv("Players_Score.csv")
fixture <- read.csv("Fixture.csv", header=F)
teams <- read.csv("Teams.csv")
```

## Data Analysis
Research question 1:

Insert text here

```{r}
teams %>% arrange(desc(Points)) %>% head(10) %>%
  ggplot(aes(x=reorder(Team, Points),  y=Points, fill=Team)) + geom_bar(stat="identity") +
  coord_flip() +
  labs(x="Team", y="Points", title="Top 10 teams by points")
```

Insert text here.


Research question 2:

Insert text here

```{r}
ggplot(data=score, aes(x=age)) + geom_histogram(fill="steelblue", bins=30) + 
  labs(x="Age", title="Distribution of ages")
```

Insert text here.



Research question 3:

Insert text here

```{r}
ggplot(data=score, aes(x=PS, y=Rating)) + geom_point() +
  geom_smooth(method="lm") +
  labs(x="PS", y="Rating", title="Scatter plot of ratingcs PS")
```

Insert text here.



Research question 4:

Insert text here

```{r}
stats$total <- as.numeric(gsub(",", "", stats$total))
stats %>% filter(club %in% c("Forward - Vitesse", "Forward - CSKA")) %>%
  ggplot(aes(x=club, y=total)) + geom_boxplot()
```

Insert text here.

